### ISSUE TITLE
Druid Remove Hungry Vines add AA entrap for snare line

### ISSUE THREAD

**Issue by destre31** [DerpleMQ2/rgmercs#103]
Test with level 76 druid. Spell Hungry Vines. Only 12 seconds by the time the mob runs spell has worn off. Easy fix is just remove it from class config file. But better fix would be like Rangers config file to use the AA entrap.  But im not a coder so not sure how to fix it since i do not see the same dosnare option.

**Comment by DerpleMQ2** [comment]
I added Entrap to the DRU config as an AA - please confirm it is ID 219.
I also added a DoSnare option to druids.

**Comment by DerpleMQ2** [comment]
https://github.com/DerpleMQ2/rgmercs/commit/3893a6454e929622c80dd84ec242590ed8b4cd3f

**Comment by destre31** [comment]
sweet now he entraps right away :)

**Comment by destre31** [comment]
Yes ty. Works great now.
