### ISSUE TITLE
DoMount Buff Only tries to cast indoor

### ISSUE THREAD

**Issue by RobbanEQ** [DerpleMQ2/rgmercs#110]
Choosing Buff Only in the Do Mount meny makes characters try to do it indoors.

**Comment by DerpleMQ2** [comment]
I am looking at the code and I am not sure how this is possible as the first check we do in ShouldMount() is checking if you are out side:

`    local passBasicChecks = not RGMercUtils.GetSetting('DoMelee') and RGMercUtils.GetSetting('MountItem'):len() > 0 and mq.TLO.Zone.Outdoor()`

**Comment by RobbanEQ** [comment]
must be 2 defferent checks then. 
If I choose Mount it won't try. But choosing Buff Only it spams trying to mount.

**Comment by cannonballdex** [comment]
My issue was that I had placed my mount item under clickies. Once I removed it from there and only had the mount in the mount slot did it quit trying to cast indoors.
