### ISSUE TITLE
[MAG] Self ModRod isn't used

### ISSUE THREAD

**Issue by AlgarDude** [DerpleMQ2/rgmercs#146]
The entry to use it only checks that we have the item we've dragged to the setting panel, there is no code to use it.

**Comment by AlgarDude** [comment]
```
 {
                name = "SelfModRod",
                type = "Item",
                cond = function(self)
                    return mq.TLO.FindItemCount(RGMercUtils.GetSetting('SelfModRod'))() == 0 and mq.TLO.Me.PctMana() < RGMercUtils.GetSetting('ModRodManaPct') and
                        mq.TLO.Me.PctHPs() >= 60
                end,
            },
```

**Comment by AlgarDude** [comment]
It appears this entry may be unnecessary, at a brief glance I suspect the name of the SelfModRod is being picked up by ClickModRod and its being used from there.

**Comment by DerpleMQ2** [comment]
It is an item type so the entry handler will click the item without any custom code.
