### ISSUE TITLE
85 heroic PAL tries to summon arrows with Huntsman's Ethereal Quiver

### ISSUE THREAD

**Issue by RobbanEQ** [DerpleMQ2/rgmercs#153]
Getting smap of 'You are not sufficient level to use this item', because its lvl 90 required.
lvl check on using that item maybe or something? 
Remove it from the code? Does any lvl 90 or higher PAL actually use a bow?

**Comment by AlgarDude** [comment]
A level check like 
`mq.TLO.Me.Level() > 89` 
should be sufficient here, since we already have a setting to use the quiver or not in the class config.
I try not to remove existing functionalilty based on my personal opionion unless I am reasonably sure that it is _detrimental_ to have it.

**Comment by AlgarDude** [comment]
One note, I would raise the minimim arrow count when you do that, as I seem to remember an issue from another class wherein they would run out of arrows between the time they would use this in normal play.
