### ISSUE TITLE
When pull module is spam pulling an invalid target, spam continues until paused/cycle is otherwise broken

### ISSUE THREAD

**Issue by AlgarDude** [DerpleMQ2/rgmercs#172]
Even if you add them to the deny list (as you are attempting to pull them), you need to pause or otherwise break the cycle, otherwise, we will attempt to pull for... at least a very long time. Maybe insert a break when we add something to the list.

Also I know some other pulling tools have an auto-add to deny list, but not sure how simple that would be to code.

**Comment by DerpleMQ2** [comment]
https://github.com/DerpleMQ2/rgmercs/commit/4314049e39f7fc720c1aac84873604693ab2e881
