### ISSUE TITLE
Fix duplicate spell lineups (remedyheal vs remedyheal1 etc)

### ISSUE THREAD

**Issue by SonicZentropy** [DerpleMQ2/rgmercs#18]
I'll claim this one, just wanted a tracking reminder somewhere.  Happens for sure in more Cleric lineups, so probably also in other classes

See comments https://github.com/DerpleMQ2/rgmercs/pull/17

**Comment by DerpleMQ2** [comment]
I did a pass at this a few days ago.  This issue might be cloasable now.
