### ISSUE TITLE
Error on low level BST with Do Buffs on (Project Lazarus)

### ISSUE THREAD

**Issue by ghuff07** [DerpleMQ2/rgmercs#200]
This error repeats continuously until Do Buffs is disabled on the BST. The character is currently level 6, but this has occurred since level 1.

[Dallvut:ERROR  (rgmercs_utils.lua::SafeCallFunc():1456)] <70945.046> Condition check failed - Entry(UnityBuff), condArg(NULL), condTarg(Dallvut)
	...acroQuest\lua\rgmercs\class_configs\bst_class_config.lua:1149: attempt to index field 'AtkHPBuff' (a nil value)

![Screenshot 2024-09-19 090036](https://github.com/user-attachments/assets/e8d61fca-129c-4d54-a56f-98066122e01a)

**Comment by DerpleMQ2** [comment]
Fixed in next build.
