### ISSUE TITLE
New low level BST issue on Project Lazarus relating to buffs

### ISSUE THREAD

**Issue by ghuff07** [DerpleMQ2/rgmercs#203]
New error relating to BST buffs on Project Lazarus:

[Dallvut:ERROR  (rgmercs_utils.lua::SafeCallFunc():1456)] <82667.321> Condition check failed - Entry(UnityBuff), condArg(NULL), condTarg(Dallvut)
	...Project Lazarus\MacroQuest\lua\rgmercs\modules\class.lua:205: attempt to index field 'TempSettings' (a nil value)

**Comment by DerpleMQ2** [comment]
Oops I did a typo. fixed.
