### ISSUE TITLE
You can only switch between stances when you have a mercenary! spam

### ISSUE THREAD

**Issue by gnuchris** [DerpleMQ2/rgmercs#29]
thanks for this, its pretty amazing. When I use it with my cleric and druid I get the msg in the title constantly spamming and Im not sure why. "You can only switch between stances when you have a mercenary!"

**Comment by DerpleMQ2** [comment]
Is this stemming from a /stance command? Because this happens very infrequently in RGMercs and each time we check if you have a merc active...

**Comment by gnuchris** [comment]
The server I play on doesn't have mercenarys,and from memory I think you have some tick box to turn off mercenarys, so I did that and it stopped the spam. :)

**Comment by DerpleMQ2** [comment]
Yes there is a DoMercenary option that you can turn off. I will close this then.

**Comment by gnuchris** [comment]
Thanks
