### ISSUE TITLE
Berserker doesn't summon axes (version 2024-04-16)

### ISSUE THREAD

**Issue by JoeBostic** [DerpleMQ2/rgmercs#34]
The Berserker class doesn't summon axes. All the code is in place to do so, but there is a bug. The code that summons axes calls the routine FindItemBankCount() but should probably be calling FindItemCount(). If I change the code to call FindItemCount() it will summon axes normally.

**Comment by DerpleMQ2** [comment]
I do accept PRs for this project do you have any desires to fix this and send me a PR for it?  If not I will get to it as soon as I can.

**Comment by DerpleMQ2** [comment]
I think this is fixed now please re-test.
