### ISSUE TITLE
Text error "Do Check Click" should be "Do Chest Click"  (version 2024-04-16)

### ISSUE THREAD

**Issue by JoeBostic** [DerpleMQ2/rgmercs#36]
There is an option that is labeled "Do Check Click", but the tooltip describes it as doing a "chest" item click. I think the label probably needs to read "Do Chest Click".

**Comment by DerpleMQ2** [comment]
Fixed with: https://github.com/DerpleMQ2/rgmercs/commit/1dc00d4b6ba2219e27ec7fb85a3ced3a7c15d61b
