### ISSUE TITLE
Suggestion: Show paused state in RGMercs UI title bar.  (version 2024-04-16)

### ISSUE THREAD

**Issue by JoeBostic** [DerpleMQ2/rgmercs#38]
It is great that you can pause and unpause RGMercs with macros, but you can't tell if RGMercs is paused or not without opening up the dialog box. It is handy to keep RGMercs dialog box collapsed to just the title bar. Showing the pause state on this title bar would be a greatly appreciated Quality of Life feature. You could change the title bar text to add "<paused>" when in paused state, for example.

**Comment by DerpleMQ2** [comment]
This is shown in the giant button. if I rename the title bar it will cause inmgui to think its a new window and change its positioning info etc.
