### ISSUE TITLE
Clickie-buffs can repeat cast over and over in a loop (version 2024-04-16)

### ISSUE THREAD

**Issue by JoeBostic** [DerpleMQ2/rgmercs#39]
If you have a clickie-item and configure RGMercs to use it AND the buff that the click casts won't stick (because of a more powerful buff on the target, for example), RGMercs will continually try to click the item in a never-ending loop. Not easy solution comes to mind unless RGMercs can detect when an effect bounces rather than just looking to see if the affect is on the target. The workaround for this bug is to only use clickies that cannot bounce.

**Comment by DerpleMQ2** [comment]
https://github.com/DerpleMQ2/rgmercs/commit/375e0daedf66a412e3e53b863af3068a7c2e7762
