### ISSUE TITLE
The Beastlord goes into an endless warder-player-warder targeting loop (version 2024-04-16)

### ISSUE THREAD

**Issue by JoeBostic** [DerpleMQ2/rgmercs#40]
The Beastlord (tested at level 104) keeps targeting himself, then targets the warder, then targets himself. Over and over and over. Not casting, just target toggling rapidly. This only happens if I have the Beastlord epic weapon on me. If I put the epic weapon in the bank, the weird targeting behavior stops. I presume this is a case where RGMercs is trying to cast the warder buff from the epic item, but it cannot do so for some reason so it just keeps trying over and over.

**Comment by AlgarDude** [comment]
BST class config has gone through mulltiple iterations of updates since this was  posted, and I have a suspicion this was previously addressed. Please let me know if this isn't the case.
