### ISSUE TITLE
The Monk is not casting "Disciple's Aura" (version 2024-04-16)

### ISSUE THREAD

**Issue by JoeBostic** [DerpleMQ2/rgmercs#41]
The monk (tested at level 63) does not cast the Disciple's Aura even though the rotation shows a green checkmark next to it. I seem to recall that the macro version of RGMercs also had this issue. It easy to work around -- just recast the aura manually every time you zone. Not sure if this helps, but the ability is called "Disciple's Aura" but the buff is called "Disciple's Aura Effect".

**Comment by DerpleMQ2** [comment]
https://github.com/DerpleMQ2/rgmercs/commit/d435460ce7aeb6fbf5e586034e62db4e61a5a976
