### ISSUE TITLE
Suggestion: Don't auto-stand unless combat starts.  (version 2024-04-16)

### ISSUE THREAD

**Issue by JoeBostic** [DerpleMQ2/rgmercs#42]
RGMercs will auto-stand your character when not medding. This means you can't look at the spell book or memorize new spells unless you pause RGMercs. It would be a great quality of life to only auto-stand when combat starts. Maybe use the extended target tracking to determine if combat has started? This is how the macro version of RGMercs behaved and it worked out well.

**Comment by DerpleMQ2** [comment]
This is a contentious one. IIRC this was changed because other people didn't want them sitting during pulls. I don;t have a strong feeling about it - I m right make it just an option.

**Comment by DerpleMQ2** [comment]
Fixed: https://github.com/DerpleMQ2/rgmercs/commit/d740af68eca8551d5b9c3c3cc93a0232b6f9aa76
