### ISSUE TITLE
Suggestion: Move MAG spell with long cooldown off of the bottom spell gem (version 2024-04-16)

### ISSUE THREAD

**Issue by JoeBostic** [DerpleMQ2/rgmercs#43]
The mage will put the spell Gather Magnitude in the bottom spell gem. This spell gem gets swapped out frequently whenever a buff or summon or other utility spell is needed by RGMercs. This means that the Gather Magnitude spell is almost always in an artificial cooldown state. I was able to fix this issue in the lua code by moving the pet heal spell to the bottom spell gem slot. Now Gather Magnitude is always ready when needed.  This probably applies to all Gather Mana line of spells and might even affect the WIZ class to, but I didn't check it.

**Comment by DerpleMQ2** [comment]
CAn you push a pr?

**Comment by DerpleMQ2** [comment]
Fixed.
