### ISSUE TITLE
Suggestion: Anti-suicide code for NEC lich line (version 2024-04-16)

### ISSUE THREAD

**Issue by JoeBostic** [DerpleMQ2/rgmercs#44]
I wish there was code that prevented a NEC class from killing himself because of lich spells. Walk away while your NEC is in PoK and when you get back, he is dead. lol. An ideal solution might have a few configurable values:

- Don't cast any lich spell if mana is above some defined %
- CANCEL any lich buffs (and don't cast any either) when health is below some defined %
- CANCEL any lich buffs when mana reaches 100%

**Comment by DerpleMQ2** [comment]
https://github.com/DerpleMQ2/rgmercs/commit/56904b05810910ac9fc859c5a4a3bf4dbfa389b8
