### ISSUE TITLE
MAG class not putting fire bolt nukes into spell gems (version 2024-04-16)

### ISSUE THREAD

**Issue by JoeBostic** [DerpleMQ2/rgmercs#45]
Below level 70, the MAG class will not memorize the fire bolt nuke line. It has the spell in the rotation but doesn't memorize it. The bug is in the code that puts a spell into gem slot #3. It is using "FireNuke1" when it should be using "FireBoltNuke". The spell line "FireNuke1" is already being memmed into spell geam #1.

**Comment by DerpleMQ2** [comment]
Fixed on https://github.com/DerpleMQ2/rgmercs/commit/7d435cbb4fe5aed12e70c73f7372d78c1a6260f6
