### ISSUE TITLE
Suggestion: Change title bar color of UI to reflect paused state?

### ISSUE THREAD

**Issue by JoeBostic** [DerpleMQ2/rgmercs#48]
Would it be possible to change the color of the title bar according to the paused state of RGMercs? This would allow a player to see if RGMercs was paused without expanding the configuration dialog. Maybe with an ImGuiStyleVar setting?

**Comment by DerpleMQ2** [comment]
Color we can change but color can be overwritten by the user with a custom theme. So I will have to think about how to do this.  IE the SK uses red for the color format already.

**Comment by JoeBostic** [comment]
Making the title bar 50% transparent might also work to let the player know paused state -- presuming setting transparency is possible.

**Comment by DerpleMQ2** [comment]
Also that can be set by the user (its a UI config option.)

**Comment by DerpleMQ2** [comment]
https://github.com/DerpleMQ2/rgmercs/commit/68220a61eb5ddfb4c00b1715d7d086c90b2d345d

Will have a 1time breaking change but this works now.
