### ISSUE TITLE
Safe Targeting seems to not be working (version 2024-04-16)

### ISSUE THREAD

**Issue by JoeBostic** [DerpleMQ2/rgmercs#49]
When "Use Safe Targeting" is on, my character will still rush over to engage mobs that are already engaged by other players. I can repeat this every time by following these steps:

1. Create a new character and enter the tutorial zone. I used a Ranger class, if that makes any difference.
2. Ensure "Use Safe Targeting" is on and "Auto Target" is on. These are on by default, so you won't need to change anything.
3. Set "Assist Range" to 200
4. Walk around the zone or follow someone at a good distance. As soon as they engage a mob, your character will try to rush up to engage it too.
5. I had my character set as "main assist" and my mercenary set as "main tank" through the in-game normal role menus, if that makes any difference. I didn't try varying these settings.

**Comment by DerpleMQ2** [comment]
Pushed a change now that will print out what IsSafeName returns.

You will want to turn logging to verbose and then do

`/rgl setlogfilter IsSafeName`

Caps matters so do it exactly like that. And then look at the console to see what it is returning there.
