### ISSUE TITLE
Will always dismount if "Do Mount" is off even when not in combat (version 2024-04-16)

### ISSUE THREAD

**Issue by JoeBostic** [DerpleMQ2/rgmercs#50]
Not sure if this is intended, but if "Do Mount" is set to "off", I can't use my mount even when out of combat. I was presuming that the "off" setting would only apply in combat. Otherwise, I have to turn off RGMercs to mount-travel. I was hoping that "Off" setting would dismount when combat starts, not dismount otherwise.

Maybe only dismount in combat if "off" setting is chosen?

**Comment by DerpleMQ2** [comment]
This is intended. RGMercs is not setup to be semi-automation it has no idea why you are on a mount all it knows is that mount shouldn't be on.
