### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Myystroe** [DerpleMQ2/rgmercs#52]
Don't know where to ask questions as the discussion topic is removed

Issues:
(I did not see a specific area for illusion and familiar buffs like the mount ones)
Familiar seems to check for the familiar instead of the familiar buff
Jann's mask looks for illusion instead illusion buff
It also doesn't seem to attack combat dummy so I can't without going out and trying it out which I haven't had time to do
--------------------------------
Questions:
Are there a list of text commands for this lua or do you have to manually click ever change?
Are raid assists in the OAassists or is that supported?
Can you change spell/song order?
I see a ton of stuff that is marked as conditions not met, I assume those will be met during combat?

**Comment by DerpleMQ2** [comment]
We have a whole forum now: https://www.redguides.com/community/forums/rgmercs-lua.196/

you can use /rgl help and /rgl set show
