### ISSUE TITLE
Set New Camp Here

### ISSUE THREAD

**Issue by cannonballdex** [DerpleMQ2/rgmercs#54]
When selecting Set New Camp Here or /rgl campon
Goes into a loop of trying to drop a campfire and not selecting a campfire to drop.

**Comment by cannonballdex** [comment]
Ok so I had looked at the campfire settings was set to Empowered Woodelf. Not sure if this got changed some where along the line, but maybe default should be set to Regular Campfire.

**Comment by DerpleMQ2** [comment]
https://github.com/DerpleMQ2/rgmercs/commit/bad60e8c08e0a0bb2eede13992fbda25c126f329
