### ISSUE TITLE
Suggestion: Add PullTime, PullRestTime

### ISSUE THREAD

**Issue by ladon-radim** [DerpleMQ2/rgmercs#55]
PullTimeMin = Time to pull/hunt/chain for before forcing downtime
PullTimeMax = for randomness
PullTimeRest = How long to force a downtime cycle for rebuffs (SoW!) after PullTime has elapsed and XTarget is 0

Pullers should [optionally] prioritize self-buffing or requesting a sow over making pulls. Crunchy ogre bodies.

**Comment by AlgarDude** [comment]
There is currently a user-configured delay that is invoked after each kill and a second user-configured delay that controls how long after movement you will wait to cast buffs. Between adjusting those, they are likely enough for most usecases. Programing the above is possible, but very subjective and may not fit all playstyles. 

I believe that the best course of action to get exactly what you are asking for is a LEM that will start and stop pulling based off of time conditions or the (lack of) presence of a particular buff.
