### ISSUE TITLE
Bug: Changing <any> online character's Camp Distance using +/- breaks the camp of all online users.

### ISSUE THREAD

**Issue by ladon-radim** [DerpleMQ2/rgmercs#56]
"Why isn't this group doing anything?"
<tests>
ohno

**Comment by AlgarDude** [comment]
There have been numerous adjustments to camp and pull settings since the date of this issue (and I wasn't collaborating on the project at that time). 

Can you confirm that this is still happening?
@DerpleMQ2 , do you remember any specific issue or fix aimed at the above?

**Comment by DerpleMQ2** [comment]
Which camp distance is this referring to? I adjust it from time to time but I don't think it breaks my camp.
