### ISSUE TITLE
Add UI option to add pull allow/deny mobs

### ISSUE THREAD

**Issue by Hamletf** [DerpleMQ2/rgmercs#58]
Currently cannot add mobs to pull allow without targeting them first, would like to be able to add option to allow/deny without having to edit the .ini

**Comment by cannonballdex** [comment]
Another note on similar lines. When you try to attack an un attackable mob and click the button to add to ignore list, you have to restart rgmercs to move to the next target. Need some type of esc and move on command after adding target to ignore.

**Comment by destre31** [comment]
My experience is do not need to restart. I just click stop Pulls and it goes back to camp and chooses new mob not on ignore list to pull once i click on start pulls.

**Comment by AlgarDude** [comment]
Apologize for the necro.
I understand that you are specifically asking for a text box, but this can already be accomplished by using /rgl pullallow or pull deny:
`/rgl pullallow "Algar's Mom"`
