### ISSUE TITLE
Level 52 Enchanter Pet Haste

### ISSUE THREAD

**Issue by destre31** [DerpleMQ2/rgmercs#69]
My Enchanter who is level 52 constantly tries to cast clerity on the pet, yet keeps targeting the enchanter and not the pet. Causes a mana issue.

**Comment by AlgarDude** [comment]
I believe I see the issue, will lump this in with some other enchanter updates I'm making.

**Comment by AlgarDude** [comment]
https://github.com/DerpleMQ2/rgmercs/pull/73
should resolve this issue.

**Comment by destre31** [comment]
seems fixed closing issue
