### ISSUE TITLE
Group buffs being repeated (up to) six times.

### ISSUE THREAD

**Issue by AlgarDude** [DerpleMQ2/rgmercs#81]
Group buffs commonly cast once for each member missing them at the time the script checks the group's buffs. This results in a spell being memmed, cast, and the old spell rememmed up to six times.

**Comment by RobbanEQ** [comment]
This is really annoying. Anyone knows why?

**Comment by AlgarDude** [comment]
I do know why but requires some rework beyond my ability, it's in my short list of things to bother Derple about XD

**Comment by AlgarDude** [comment]
I am testing a rework of group buffs that in part addresses this issue

**Comment by AlgarDude** [comment]
Recent changes and reworks to underlying functions seems to address this issue, and we have a few more changes in the pipe.
