### ISSUE TITLE
Delay in resuming rotations on rememorizing a spell.

### ISSUE THREAD

**Issue by AlgarDude** [DerpleMQ2/rgmercs#89]
When the last slot is used to memorize a spell temporarily, and the old spell is rememorized, automation resumes when the rememorized spell is available to cast (or when the 15 second MemorizeSpell timeout occurs), not when it is finished memorizing.

To replicate/witness, start RGL, pause after spells are set, set a spell with a high recast delay in your last gem, unpause, turn on verbose, and trigger a rebuff somehow (canceling something, etc).

**Comment by cannonballdex** [comment]
Anything to do with the Global Cooldown timer?

**Comment by AlgarDude** [comment]
Solid discussion on discord highlighting the issues and potential "fixes" last night, but its a bad idea to mem a long recast spell in your last slot as a matter of course anyway... this just magnifies it.
